require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'config/deploy.rb'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'spec/support/**/*'
    - 'tmp/**/*'

Metrics/AbcSize:
  Exclude:
    - 'app/models/pulfalight/requests/aeon_external_request.rb'
    - 'lib/pulfalight/traject/ead2_component_config.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'config/routes.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/models/solr_document.rb'
    - 'app/controllers/catalog_controller.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/models/pulfalight/requests/aeon_external_request.rb'
    - 'app/models/solr_document.rb'
    - 'lib/pulfalight/traject/ead2_component_config.rb'
    - 'lib/tasks/pulfalight.rake'
Naming/PredicateName:
  Exclude:
    - 'app/models/solr_document.rb'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/pulfalight/traject/ead2_component_config.rb'
Metrics/ModuleLength:
  Exclude:
    - 'lib/pulfalight/traject/ead2_component_config.rb'
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/pulfalight/traject/ead2_component_config.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/catalog_view_spec.rb'
    - 'spec/features/traject/ead2_indexing_spec.rb'
    - 'spec/models/solr_document_spec.rb'
    - 'spec/requests/catalog_request_spec.rb'
    - 'spec/services/robots_generator_service_spec.rb'
Style/StringLiterals:
  EnforcedStyle: double_quotes
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/models/user_spec.rb'
