defaults: &defaults
  external_universal_viewer_url: "https://figgy.princeton.edu/viewer"
  archivespace_url: "https://asqa.lyrtech.org/staff/api"
  archivespace_user: <%= ENV["ASPACE_USER"] %>
  archivespace_password: <%= ENV["ASPACE_PASSWORD"] %>
  aeon_url: 'https://lib-aeon.princeton.edu/aeon/Aeon.dll'

development:
  <<: *defaults

test:
  <<: *defaults
  archivespace_url: "https://aspace.test.org/staff/api"
  archivespace_user: "test"
  archivespace_password: "password"

production:
  <<: *defaults
  archivespace_url: <%= ENV["ASPACE_URL"] || "https://asqa.lyrtech.org/staff/api" %>

staging:
  <<: *defaults
  archivespace_url: <%= ENV["ASPACE_URL"] || "https://asqa.lyrtech.org/staff/api" %>
