cotsen: 'Firestone Library'
ex: 'Firestone Library'
gax: 'Firestone Library'
ga: 'Firestone Library'
mss: 'Firestone Library'
njpg: 'Firestone Library'
thx: 'Firestone Library'
wa: 'Firestone Library'
hsvc: 'Firestone Library'
hsvg: 'Firestone Library'
hsvm: 'Firestone Library'
hsvr: 'Firestone Library'
mudd: 'Mudd Manuscript Library'
rcppa: 'ReCAP'
rcppf: 'ReCAP'
rcpph: 'ReCAP'
rcpxc: 'ReCAP'
rcpxg: 'ReCAP'
rcpxm: 'ReCAP'
rcpxr: 'ReCAP'
selectors: 'ReCAP'
flm: 'Firestone Library'
st: 'Engineering Library'
anxb: 'Annex B'
ppl: 'Plasma Physics Library'
